### ISSUE TITLE
Unexpected error is not printed to the log

### ISSUE THREAD

**Issue by alexbudarov** [Haulmont/jmix-ui#114]
Try to open screen that isn't permitted to the user.

You see this dialog:
![image](https://user-images.githubusercontent.com/6158807/94919338-638a2b80-04c5-11eb-99b8-22f0643be996.png)

If you don't have  "cuba.gui.showExceptionDetails" permission - then you don't see even exception details.

Expected:
exception is also printed to the log (Run configuration console)

Actual:
exception is not logged

**Comment by glebfox** [comment]
Unexpected errors are printed to the log regardless of `cuba.gui.showExceptionDetails` permission, e.g.:

<img width="703" alt="Screenshot 2020-12-08 at 16 11 53" src="https://user-images.githubusercontent.com/6077149/101482522-49127980-3970-11eb-8259-baa386f58bea.png">

```
Caused by: io.jmix.core.security.AccessDeniedException: SCREEN ikna_User.browse

	at io.jmix.ui.sys.ScreensImpl.checkPermissions(ScreensImpl.java:918) ~[jmix-ui-0.2.0-SNAPSHOT.jar:na]
	at io.jmix.ui.sys.ScreensImpl.createScreen(ScreensImpl.java:168) ~[jmix-ui-0.2.0-SNAPSHOT.jar:na]
	at io.jmix.ui.sys.ScreensImpl.create(ScreensImpl.java:150) ~[jmix-ui-0.2.0-SNAPSHOT.jar:na]
	at io.jmix.ui.menu.MenuItemCommands$ScreenCommand.createScreen(MenuItemCommands.java:306) ~[jmix-ui-0.2.0-SNAPSHOT.jar:na]
	at io.jmix.ui.menu.MenuItemCommands$ScreenCommand.run(MenuItemCommands.java:242) ~[jmix-ui-0.2.0-SNAPSHOT.jar:na]
	at io.jmix.ui.menu.SideMenuBuilder$MenuCommandExecutor.accept(SideMenuBuilder.java:272) ~[jmix-ui-0.2.0-SNAPSHOT.jar:na]
	at io.jmix.ui.menu.SideMenuBuilder$MenuCommandExecutor.accept(SideMenuBuilder.java:257) ~[jmix-ui-0.2.0-SNAPSHOT.jar:na]
	at io.jmix.ui.component.mainwindow.impl.SideMenuImpl$MenuItemImpl.menuSelected(SideMenuImpl.java:587) ~[jmix-ui-0.2.0-SNAPSHOT.jar:na]
	at io.jmix.ui.widget.JmixSideMenu$1.menuItemTriggered(JmixSideMenu.java:91) ~[jmix-ui-0.2.0-SNAPSHOT.jar:na]
	... 88 common frames omitted

```
