### ISSUE TITLE
Implement FileStorageExceptionHandler

### ISSUE THREAD

**Issue by alexbudarov** [Haulmont/jmix-ui#134]
Previously in CUBA such errors were not shown in UI, only written to log.
And it felt okay, because lack of image in file storage isn't critical to show it to the user.

![image](https://user-images.githubusercontent.com/6158807/96291064-9e797c80-0ff8-11eb-9045-88b155a6670f.png)

```
2020-10-16 21:42:22.426 ERROR 127614 --- [nio-8080-exec-9] i.j.u.exception.DefaultExceptionHandler  : Unhandled exception

java.lang.RuntimeException: Can't create FileStorageResource. An error occurred while obtaining a file from the storage
	at io.jmix.ui.component.impl.FileStorageResourceImpl.lambda$createResource$aaf49691$1(FileStorageResourceImpl.java:77) ~[jmix-ui-0.1.0-SNAPSHOT.jar:na]
	at com.vaadin.server.StreamResource.getStream(StreamResource.java:143) ~[vaadin-server-8.9.2-5-jmix.jar:8.9.2-5-jmix]
	at com.vaadin.server.AbstractClientConnector.handleConnectorRequest(AbstractClientConnector.java:697) ~[vaadin-server-8.9.2-5-jmix.jar:8.9.2-5-jmix]
	at com.vaadin.server.ConnectorResourceHandler.handleRequest(ConnectorResourceHandler.java:88) ~[vaadin-server-8.9.2-5-jmix.jar:8.9.2-5-jmix]
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1578) ~[vaadin-server-8.9.2-5-jmix.jar:8.9.2-5-jmix]
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:425) ~[vaadin-server-8.9.2-5-jmix.jar:8.9.2-5-jmix]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750) ~[javax.servlet-api-4.0.1.jar:4.0.1]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
...
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: io.jmix.core.FileStorageException: File not found: 2020/10/16/2fad33f7-549c-7b87-09ec-716bb7ffb603.png*JpaBuddy_color.png
	at io.jmix.fsfilestorage.FileSystemFileStorage.openStream(FileSystemFileStorage.java:230) ~[jmix-fsfilestorage-0.1.0-SNAPSHOT.jar:na]
	at io.jmix.fsfilestorage.FileSystemFileStorage.openStream(FileSystemFileStorage.java:57) ~[jmix-fsfilestorage-0.1.0-SNAPSHOT.jar:na]
	at io.jmix.ui.component.impl.FileStorageResourceImpl.lambda$createResource$aaf49691$1(FileStorageResourceImpl.java:75) ~[jmix-ui-0.1.0-SNAPSHOT.jar:na]
	... 74 common frames omitted
```

Sample project: (User#photo, user editor)
To reproduce, delete uploaded photo file from filestorage folder.
[userphoto.zip](https://github.com/Haulmont/jmix-ui/files/5393424/userphoto.zip)

### QA
Test project - [local-fs-demo.zip](https://github.com/Haulmont/jmix-ui/files/6074438/local-fs-demo.zip)

1) Run the application
2) Open user editor
3) Upload new photo
4) Close the user editor
5) Delete uploaded photo file from local filestorage folder (**.jmix/work/filestorage/...**)

* Actual behavior 
![image](https://user-images.githubusercontent.com/35256248/109773229-6924a280-7c18-11eb-8be6-2e96ac3bc127.png)

```
io.jmix.core.FileStorageException: File not found: fs://2021/03/03/517f92cb-7bd9-9ffe-4422-75f8eb9d1ed1.svg?name=test-photo.svg
	at io.jmix.localfs.LocalFileStorage.openStream(LocalFileStorage.java:229)
	at io.jmix.ui.component.impl.FileStorageResourceImpl.lambda$createResource$aaf49691$1(FileStorageResourceImpl.java:75)
	at com.vaadin.server.StreamResource.getStream(StreamResource.java:143)
	at com.vaadin.server.AbstractClientConnector.handleConnectorRequest(AbstractClientConnector.java:697)
	at com.vaadin.server.ConnectorResourceHandler.handleRequest(ConnectorResourceHandler.java:88)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1578)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:425)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
```
* Expected behavior 
![image](https://user-images.githubusercontent.com/35256248/109777872-9889de00-7c1d-11eb-9dcf-cf0b8d622917.png)

```
2021-03-03 12:39:54.754 ERROR 4558 --- [nio-8080-exec-9] io.jmix.localfs.LocalFileStorage         : File /IdeaProjects/demo-jmix/demo-filter/.jmix/work/filestorage/2021/03/03/bd344dac-ddf1-4622-62bc-0349f44f616a.svg not found
```

**Comment by glebfox** [comment]
CUBA shows "File not found" exception but in form of an error message instead of unexpected error dialog.
