### ISSUE TITLE
An unexpected error occurs with autoLoad usage in simplePagination component

### ISSUE THREAD

**Issue by lovtsovaik** [Haulmont/jmix-ui#206]
### Environment
Jmix framework version: 0.2.0

### Description of the bug or enhancement

1. Open the project [scrwiz.zip](https://github.com/Haulmont/jmix-ui/files/5713653/scrwiz.zip)
2. Run the application
3. Optional: open any screen in Application except of "Numbers custom container"
4. Open Application -> "Numbers custom container"
5. Open any other screen
6. Stop the app
7. Open `numbers-browse7.xml`
8. Delete `autoLoad="true"` from `simplePagination` component
9. Repeat the steps 1-5

ER: The screen is loaded without errors
AR: An error occurred on step 5: after loading total count and switch to other screen
![image](https://user-images.githubusercontent.com/73226373/102574673-c5445400-410a-11eb-820f-1128e5b28659.png)

```
Caused by: java.lang.reflect.InvocationTargetException: null
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_265]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_265]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_265]
at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_265]
at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:153) ~[vaadin-server-8.9.2-5-jmix.jar:8.9.2-5-jmix]
... 83 common frames omitted
Caused by: io.jmix.core.security.AccessDeniedException: resource: scrwiz_Numbers6.browse, type: screen, action: null
at io.jmix.ui.sys.ScreensImpl.checkPermissions(ScreensImpl.java:917) ~[jmix-ui-0.2.0.jar:na]
at io.jmix.ui.sys.ScreensImpl.createScreen(ScreensImpl.java:167) ~[jmix-ui-0.2.0.jar:na]
at io.jmix.ui.sys.ScreensImpl.create(ScreensImpl.java:149) ~[jmix-ui-0.2.0.jar:na]
at io.jmix.ui.menu.MenuItemCommands$ScreenCommand.createScreen(MenuItemCommands.java:306) ~[jmix-ui-0.2.0.jar:na]
at io.jmix.ui.menu.MenuItemCommands$ScreenCommand.run(MenuItemCommands.java:242) ~[jmix-ui-0.2.0.jar:na]
at io.jmix.ui.menu.SideMenuBuilder$MenuCommandExecutor.accept(SideMenuBuilder.java:272) ~[jmix-ui-0.2.0.jar:na]
at io.jmix.ui.menu.SideMenuBuilder$MenuCommandExecutor.accept(SideMenuBuilder.java:257) ~[jmix-ui-0.2.0.jar:na]
at io.jmix.ui.component.mainwindow.impl.SideMenuImpl$MenuItemImpl.menuSelected(SideMenuImpl.java:587) ~[jmix-ui-0.2.0.jar:na]
at io.jmix.ui.widget.JmixSideMenu$1.menuItemTriggered(JmixSideMenu.java:91) ~[jmix-ui-0.2.0.jar:na]
... 88 common frames omitted
```

**Comment by Flaurite** [comment]
Caused by: [Haulmont/jmix-ui#215](https://github.com/Haulmont/jmix-ui/issues/215)
