### ISSUE TITLE
Implement system info for entity in a table/datagrid

### ISSUE THREAD

**Issue by andreysubbotin** [Haulmont/jmix-ui#27]
```
io.jmix.ui.NoSuchScreenException: Screen 'sysInfoWindow' is not defined
	at io.jmix.ui.WindowConfig.getWindowInfo(WindowConfig.java:493)
	at io.jmix.ui.action.ShowInfoAction.showInfo(ShowInfoAction.java:78)
	at io.jmix.ui.action.ShowInfoAction.actionPerform(ShowInfoAction.java:68)
	at io.jmix.ui.component.impl.WebAbstractActionsHolderComponent.lambda$setContextMenuButtonAction$0(WebAbstractActionsHolderComponent.java:157)
	at io.jmix.ui.widget.JmixButton.fireClick(JmixButton.java:77)
	at com.vaadin.ui.Button$1.click(Button.java:57)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
```

**Comment by knstvk** [comment]
Perhaps in the datatools/datatools-ui modules.

**Comment by glebfox** [comment]
Duplicates: #64
