### ISSUE TITLE
ClassCastException is thrown after changing a property in the PropertyFilterConditionEdit

### ISSUE THREAD

**Issue by GlebDurygin** [Haulmont/jmix-ui#346]
### Minimal reproducible example
1) Add search condition for attribute with `String` datatype.
2) Select one of the operations: `EQUAL` or `CONTAINS`
3) Open configuration editor
4) Edit added property condition
5) Change operation to `IS_SET`
6) Set default value `true`
7) Save the configuration
8) Close the configuration editor

* Actual behavior:
```
java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
	at io.jmix.ui.component.impl.TextFieldImpl.convertToPresentation(TextFieldImpl.java:149)
	at io.jmix.ui.component.impl.TextFieldImpl.convertToPresentation(TextFieldImpl.java:52)
	at io.jmix.ui.component.impl.AbstractValueComponent.setValue(AbstractValueComponent.java:103)
	at io.jmix.ui.component.impl.AbstractSingleFilterComponent.setValue(AbstractSingleFilterComponent.java:316)
	at io.jmix.ui.component.propertyfilter.PropertyFilterConverter.convertToComponent(PropertyFilterConverter.java:73)
	at io.jmix.ui.component.propertyfilter.PropertyFilterConverter.convertToComponent(PropertyFilterConverter.java:38)
	at io.jmix.ui.component.groupfilter.GroupFilterConverter.convertToComponent(GroupFilterConverter.java:66)
	at io.jmix.ui.component.groupfilter.GroupFilterConverter.convertToComponent(GroupFilterConverter.java:38)
	at io.jmix.ui.action.filter.FilterEditAction.onEditScreenAfterCommit(FilterEditAction.java:186)
	at io.jmix.ui.action.filter.FilterEditAction.lambda$execute$0(FilterEditAction.java:159)
```

**Comment by maistrenkoIulia** [comment]
fixed
