### ISSUE TITLE
ClassCastException is thrown after changing an operation in the JpqlFilterConditionEdit

### ISSUE THREAD

**Issue by GlebDurygin** [Haulmont/jmix-ui#351]
### Minimal reproducible example
1) Open `Add search condition` screen
2) Click on `Create JPQL condition` button
3) Create a JPQL condition for IN operation
    ![image](https://user-images.githubusercontent.com/35256248/109488669-4b7ffd80-7a9f-11eb-9aec-1e9fb25a46a5.png)
4) Click OK
5) Open configuration editor
6) Open editor for added JPQL condition
7) Change operation to "=" (change "has in expression", "default value", "where" attributes)
    ![image](https://user-images.githubusercontent.com/35256248/109488921-a154a580-7a9f-11eb-9941-04996e551a82.png)

* Actual behaviour
```
java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Collection
	at io.jmix.ui.component.impl.ValuesPickerImpl.setValue(ValuesPickerImpl.java:27)
	at io.jmix.ui.component.impl.AbstractSingleFilterComponent.setValue(AbstractSingleFilterComponent.java:316)
	at io.jmix.ui.component.jpqlfilter.JpqlFilterConverter.convertToComponent(JpqlFilterConverter.java:76)
	at io.jmix.ui.component.jpqlfilter.JpqlFilterConverter.convertToComponent(JpqlFilterConverter.java:38)
	at io.jmix.ui.component.groupfilter.GroupFilterConverter.convertToComponent(GroupFilterConverter.java:66)
	at io.jmix.ui.component.groupfilter.GroupFilterConverter.convertToComponent(GroupFilterConverter.java:38)
	at io.jmix.ui.action.filter.FilterEditAction.onEditScreenAfterCommit(FilterEditAction.java:186)
	at io.jmix.ui.action.filter.FilterEditAction.lambda$execute$0(FilterEditAction.java:159)
```

**Comment by maistrenkoIulia** [comment]
fixed
