### ISSUE TITLE
IllegalArgumentException occurs after trying to create new entity instance with compositon attribute 

### ISSUE THREAD

**Issue by Mihail063** [Haulmont/jmix-ui#398]
*Jmix version: 1.0.0-SNAPSHOT
Jmix Studio plugin version: 1.0.SNAPSHOT2654-202
IntelliJ version: IntelliJ IDEA 2020.3.2 (Community Edition)*

1. Create an entity 
2. Create a composition attribute
3. Create a fetch plan with the created attribute
4. Create browser and editor screens with the created fetch plan
5. Run protect
6. Try to create new entity instance

AR: IllegalArgumentException occurs
```
java.lang.IllegalArgumentException: Unable to find action type: entity_open_composition
	at io.jmix.ui.sys.ActionsImpl.create(ActionsImpl.java:71)
	at io.jmix.ui.xml.layout.loader.AbstractComponentLoader.loadValuePickerDeclarativeAction(AbstractComponentLoader.java:776)
	at io.jmix.ui.xml.layout.loader.AbstractValuePickerLoader.loadDeclarativeAction(AbstractValuePickerLoader.java:56)
	at io.jmix.ui.xml.layout.loader.AbstractComponentLoader.loadActions(AbstractComponentLoader.java:575)
	at io.jmix.ui.xml.layout.loader.AbstractValuePickerLoader.loadComponent(AbstractValuePickerLoader.java:36)
	at io.jmix.ui.xml.layout.loader.EntityPickerLoader.loadComponent(EntityPickerLoader.java:38)
	at io.jmix.ui.xml.layout.loader.FormLoader.loadComponent(FormLoader.java:168)
	at io.jmix.ui.xml.layout.loader.FormLoader.loadComponents(FormLoader.java:153)
	at io.jmix.ui.xml.layout.loader.FormLoader.loadColumns(FormLoader.java:132)
	at io.jmix.ui.xml.layout.loader.FormLoader.loadComponent(FormLoader.java:87)
	at io.jmix.ui.xml.layout.loader.ContainerLoader.loadSubComponents(ContainerLoader.java:36)
	at io.jmix.ui.xml.layout.loader.ContainerLoader.loadSubComponentsAndExpand(ContainerLoader.java:74)
	at io.jmix.ui.xml.layout.loader.WindowLoader.loadComponent(WindowLoader.java:88)
	at io.jmix.ui.sys.ScreensImpl.loadWindowFromXml(ScreensImpl.java:323)
	at io.jmix.ui.sys.ScreensImpl.createScreen(ScreensImpl.java:201)
	at io.jmix.ui.sys.ScreensImpl.create(ScreensImpl.java:142)
	at io.jmix.ui.builder.EditorBuilderProcessor.createScreen(EditorBuilderProcessor.java:328)
	at io.jmix.ui.builder.EditorBuilderProcessor.buildEditor(EditorBuilderProcessor.java:88)
	at io.jmix.ui.builder.EditorBuilder.build(EditorBuilder.java:355)
	at io.jmix.ui.action.list.CreateAction.execute(CreateAction.java:344)
	at io.jmix.ui.action.list.CreateAction.actionPerform(CreateAction.java:300)
	at io.jmix.ui.component.impl.ButtonImpl.buttonClicked(ButtonImpl.java:75)
	at io.jmix.ui.widget.JmixButton.fireClick(JmixButton.java:77)
	at com.vaadin.ui.Button$1.click(Button.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:153)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:115)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:431)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:396)
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:260)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:82)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1578)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:425)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:327)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:115)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:81)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
```

**Comment by glebfox** [comment]
`entity_open_composition` was renamed to `entity_openComposition`
