### ISSUE TITLE
Add halo-theme.properties and hover-theme.properties to jmix.ui.themeConfig (port to 0.9)

### ISSUE THREAD

**Issue by glebfox** [Haulmont/jmix-ui#413]
See https://github.com/Haulmont/jmix-ui/issues/401

**Comment by DartVerder** [comment]
```
java.lang.NullPointerException: null
	at io.jmix.ui.icon.IconsImpl.getThemeIcon(IconsImpl.java:126) ~[jmix-ui-0.9.0.jar:na]
	at io.jmix.ui.icon.IconsImpl.get(IconsImpl.java:113) ~[jmix-ui-0.9.0.jar:na]
	at io.jmix.ui.xml.layout.loader.AbstractComponentLoader.getIconPath(AbstractComponentLoader.java:542) ~[jmix-ui-0.9.0.jar:na]
	at io.jmix.ui.xml.layout.loader.AbstractComponentLoader.initAction(AbstractComponentLoader.java:636) ~[jmix-ui-0.9.0.jar:na]
	at io.jmix.ui.xml.layout.loader.AbstractComponentLoader.loadDeclarativeActionDefault(AbstractComponentLoader.java:584) ~[jmix-ui-0.9.0.jar:na]
	at io.jmix.ui.xml.layout.loader.AbstractComponentLoader.loadDeclarativeAction(AbstractComponentLoader.java:565) ~[jmix-ui-0.9.0.jar:na]
	at io.jmix.ui.xml.layout.loader.WindowLoader.loadDeclarativeAction(WindowLoader.java:216) ~[jmix-ui-0.9.0.jar:na]
	at io.jmix.ui.xml.layout.loader.AbstractComponentLoader.loadActions(AbstractComponentLoader.java:560) ~[jmix-ui-0.9.0.jar:na]
	at io.jmix.ui.xml.layout.loader.WindowLoader.loadComponent(WindowLoader.java:67) ~[jmix-ui-0.9.0.jar:na]
	at io.jmix.ui.sys.ScreensImpl.loadWindowFromXml(ScreensImpl.java:323) ~[jmix-ui-0.9.0.jar:na]
	at io.jmix.ui.sys.ScreensImpl.createScreen(ScreensImpl.java:201) ~[jmix-ui-0.9.0.jar:na]
	at io.jmix.ui.sys.ScreensImpl.create(ScreensImpl.java:142) ~[jmix-ui-0.9.0.jar:na]
	at io.jmix.ui.Screens.create(Screens.java:68) ~[jmix-ui-0.9.0.jar:na]
	at io.jmix.ui.App.createTopLevelWindow(App.java:259) ~[jmix-ui-0.9.0.jar:na]
	at io.jmix.ui.JmixApp.initializeUi(JmixApp.java:68) ~[jmix-ui-0.9.0.jar:na]
	at io.jmix.ui.JmixApp.loginOnStart(JmixApp.java:36) ~[jmix-ui-0.9.0.jar:na]
	at io.jmix.ui.AppUI.setupUI(AppUI.java:336) ~[jmix-ui-0.9.0.jar:na]
	at io.jmix.ui.AppUI.init(AppUI.java:265) ~[jmix-ui-0.9.0.jar:na]
```

**Comment by glebfox** [comment]
@DartVerder The provided fix is intended to fix this exception, not add it. According to your _stack trace_, you've tested on **0.9.0 release** version instead of _SNAPSHOT_.
