### ISSUE TITLE
PropertyFilterCondition has no default value for the captionPosition attribute

### ISSUE THREAD

**Issue by GlebDurygin** [Haulmont/jmix-ui#419]
- Jmix version: 1.0.0-SNAPSHOT
- Jmix Studio plugin version: 1.0.SNAPSHOT2681-202
- IntelliJ version: IntelliJ IDEA 2020.3.2 (Community Edition)

### Minimal reproducible example:
run attached in ticket app -> key value browser
add search condition -> add property -> OK
![image](https://user-images.githubusercontent.com/66992566/113155834-831ec880-924a-11eb-8717-fec10b8327ce.png)

* Actual behavior :
```
java.lang.NullPointerException
	at io.jmix.ui.component.impl.AbstractSingleFilterComponent.updateCaption(AbstractSingleFilterComponent.java:220)
	at io.jmix.ui.component.impl.PropertyFilterImpl.updateCaption(PropertyFilterImpl.java:280)
	at io.jmix.ui.component.impl.PropertyFilterImpl.setOperationInternal(PropertyFilterImpl.java:183)
	at io.jmix.ui.component.impl.PropertyFilterImpl.setOperation(PropertyFilterImpl.java:150)
	at io.jmix.ui.component.propertyfilter.PropertyFilterConverter.convertToComponent(PropertyFilterConverter.java:67)
	at io.jmix.ui.component.propertyfilter.PropertyFilterConverter.convertToComponent(PropertyFilterConverter.java:39)
	at io.jmix.ui.action.filter.FilterAddConditionAction.lambda$initDefaultSelectHandler$1(FilterAddConditionAction.java:158)
	at io.jmix.ui.screen.StandardLookup.lambda$select$3(StandardLookup.java:197)
	at io.jmix.ui.util.SuccessOperationResult.then(SuccessOperationResult.java:40)
	at io.jmix.ui.screen.StandardLookup.select(StandardLookup.java:197)
	at io.jmix.ui.app.filter.condition.AddConditionScreen.onEditScreenAfterCommit(AddConditionScreen.java:201)
```

### QA
Test project - 
[key-value-filtering.zip](https://github.com/Haulmont/jmix-ui/files/6129609/key-value-filtering.zip)

**Comment by maistrenkoIulia** [comment]
verified
