### ISSUE TITLE
UI is not updated if the user logged in from another browser tab

### ISSUE THREAD

**Issue by Flaurite** [Haulmont/jmix-ui#581]
### Description

In CUBA we have a "mechanism" of informing/updating the UI if the session was changed in another tab.

For instance, if we open two browser tabs with the Login screen and perform login with different users, the first tab will be notified (system notification) that the session was changed in another tab.
Also, there is an `isForceRefreshAuthenticatedTabs` app property. If it is set to "true" the first tab from the example above will be automatically updated (without notification).

In Jmix this functionality does not work and `isForceRefreshAuthenticatedTabs` property respectively.

Note, consider to correct usage of `isForceRefreshAuthenticatedTabs` in the `App#removeAllWindows()`.

### Solution

* `isForceRefreshAuthenticatedTabs` app property is removed as it has no use anymore
*  When a user is logged in in one Browser Tab, the other will be notified and asked to refresh even if the Login screen is opened on them, i.e. the first login takes precedence. Note that this behavior differs from CUBA.

**Comment by knstvk** [comment]
Cannot login to REST:
```
2021-10-11 18:45:10.033 ERROR 63795 --- [nio-8080-exec-9] o.s.s.o.provider.endpoint.TokenEndpoint  : Handling error: ScopeNotActiveException, Error creating bean with name 'ui_App': Scope 'vaadin-session' is not active for the current thread; consider defining a scoped proxy for this bean if you intend to refer to it from a singleton; nested exception is java.lang.IllegalStateException: No VaadinSession bound to current thread
org.springframework.beans.factory.support.ScopeNotActiveException: Error creating bean with name 'ui_App': Scope 'vaadin-session' is not active for the current thread; consider defining a scoped proxy for this bean if you intend to refer to it from a singleton; nested exception is java.lang.IllegalStateException: No VaadinSession bound to current thread
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:383) ~[spring-beans-5.3.10.jar:5.3.10]
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.10.jar:5.3.10]
    at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1154) ~[spring-context-5.3.10.jar:5.3.10]
    at org.springframework.context.event.ApplicationListenerMethodAdapter.getTargetBean(ApplicationListenerMethodAdapter.java:371) ~[spring-context-5.3.10.jar:5.3.10]
    at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:336) ~[spring-context-5.3.10.jar:5.3.10]
    at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:229) ~[spring-context-5.3.10.jar:5.3.10]
    at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:166) ~[spring-context-5.3.10.jar:5.3.10]
    at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.10.jar:5.3.10]
    at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.10.jar:5.3.10]
    at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.10.jar:5.3.10]
    at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421) ~[spring-context-5.3.10.jar:5.3.10]
    at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378) ~[spring-context-5.3.10.jar:5.3.10]
    at io.jmix.securityoauth2.impl.UserPasswordTokenGranter.publishInteractiveAuthenticationSuccessEvent(UserPasswordTokenGranter.java:94) ~[jmix-security-oauth2-1.1.0-SNAPSHOT.jar:na]
```
