### ISSUE TITLE
Hot deploy of newly created screens

### ISSUE THREAD

**Issue by knstvk** [Haulmont/jmix-ui#582]
- Run the app
- Create a new entity browse screen in Studio
- Switch to the running app, logout and login again
- You will see the new menu item for the new screen
- Click the menu, you'll see an exception:

```
io.jmix.ui.NoSuchScreenException: Screen 'sample_Product.browse' is not defined
	at io.jmix.ui.WindowConfig.getWindowInfo(WindowConfig.java:486)
	at io.jmix.ui.menu.MenuItemCommands$ScreenCommand.run(MenuItemCommands.java:241)
	at io.jmix.ui.menu.SideMenuBuilder$MenuCommandExecutor.accept(SideMenuBuilder.java:272)
	at io.jmix.ui.menu.SideMenuBuilder$MenuCommandExecutor.accept(SideMenuBuilder.java:257)
	at io.jmix.ui.component.mainwindow.impl.SideMenuImpl$MenuItemImpl.menuSelected(SideMenuImpl.java:587)
	at io.jmix.ui.widget.JmixSideMenu$1.menuItemTriggered(JmixSideMenu.java:91)
```

**Comment by imorenov94** [comment]
**TC1**
**Environment:** 
Jmix version: 1.1.0-SNAPSHOT
Jmix Studio plugin version: 1.1.SNAPSHOT3595-212
IntelliJ version: IntelliJ IDEA 2021.2.2 (Ultimate Edition)
OS: Win10
**Steps:**
1. Create a new project
2. Create a new entity
3. Run the app
4. Add any browser screen to the entity
5. Navigate into the app and verify that screen has been added after hot deploy
6. Restart the app
7. Navigate to the created screen

**ER:** The screen should be shown in the app
**AR:** The screen hasn't shown
