### ISSUE TITLE
Exceptions when working with first inserted into table "long identity" entity

### ISSUE THREAD

**Issue by alexbudarov** [Haulmont/jmix-ui#62]
Project: attached
[jfresh2.zip](https://github.com/Haulmont/jmix-ui/files/5281491/jfresh2.zip)

Cousine:
```
@Table(name = "JFRESH2_COUSINE")
@Entity(name = "jfresh2_Cousine")
public class Cousine implements JmixEntity {
    private static final long serialVersionUID = -3957794063409391217L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID", nullable = false)
    private Long id;

    @InstanceName
    @NotNull
    @Column(name = "NAME", nullable = false, unique = true)
    private String name;
```

Dish:
```
@Table(name = "JFRESH2_DISH")
@Entity(name = "jfresh2_Dish")
public class Dish implements JmixEntity {
    private static final long serialVersionUID = 5560524045913505287L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID", nullable = false)
    private Long id;

    @InstanceName
    @NotNull
    @Column(name = "NAME", nullable = false)
    private String name;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "COUSINE_ID")
    private Cousine cousine;
```

- create new empty database (by deleting .jmix/hsqldb subfolder)
- launch project
- open Cousine browser
- create "Russian" cousine
- open Dish browser

### Case number 1
- Try to create new Dish "Pelmeni" with Russian cousine
Exception occurs:
```
java.lang.IllegalStateException: An attempt to save an entity with reference to some not persisted entity. All newly created entities must be saved in the same transaction. Put all these objects to the CommitContext before commit.
	at io.jmix.data.impl.OrmDataStore.handleCascadePersistException(OrmDataStore.java:1173)
	at io.jmix.data.impl.OrmDataStore.save(OrmDataStore.java:652)
	at io.jmix.core.impl.DataManagerImpl.save(DataManagerImpl.java:153)
	at io.jmix.ui.model.impl.DataContextImpl.commitToDataManager(DataContextImpl.java:657)
	at io.jmix.ui.model.impl.DataContextImpl.performCommit(DataContextImpl.java:639)
	at io.jmix.ui.model.impl.DataContextImpl.commit(DataContextImpl.java:600)
	at io.jmix.ui.screen.StandardEditor.lambda$commitChanges$4(StandardEditor.java:373)
	at io.jmix.ui.screen.StandardEditor.commitChanges(StandardEditor.java:388)
	at io.jmix.ui.screen.StandardEditor.closeWithCommit(StandardEditor.java:524)
	at io.jmix.ui.screen.StandardEditor.commitAndClose(StandardEditor.java:503)
	at io.jmix.core.common.event.EventHub.publish(EventHub.java:170)
	at io.jmix.ui.action.BaseAction.actionPerform(BaseAction.java:220)
	at io.jmix.ui.component.impl.WebButton.buttonClicked(WebButton.java:65)
	at io.jmix.ui.widget.JmixButton.fireClick(JmixButton.java:77)
	at com.vaadin.ui.Button$1.click(Button.java:57)
```
- continue. Create "French" cousine.
- try to create "Ratatui" dish with "French" cousine.
- It suddenly works!

### Case number 2
- Create dish "Coca Cola" with cousine == null
- Try to edit this dish and set cousine = French. It works.
- Try to edit this dish and set cousine = Russian. It fails with another exception:
```
2020-09-25 12:36:36.576  WARN 616 --- [nio-8080-exec-7] eclipselink.logging.all                  : Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.7.1-jmix): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLIntegrityConstraintViolationException: integrity constraint violation: unique constraint or index violation; UC_JFRESH2_COUSINE_NAME table: JFRESH2_COUSINE
Error Code: -104
Call: INSERT INTO JFRESH2_COUSINE (NAME) VALUES (?)
	bind => [Russian]
Query: InsertObjectQuery(com.company.jfresh2.entity.Cousine-0 [managed,detached])

org.hsqldb.HsqlException: integrity constraint violation: unique constraint or index violation; UC_JFRESH2_COUSINE_NAME table: JFRESH2_COUSINE
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.Constraint.getException(Unknown Source)
	at org.hsqldb.index.IndexAVL.insert(Unknown Source)
	at org.hsqldb.persist.RowStoreAVL.indexRow(Unknown Source)
	at org.hsqldb.TransactionManager2PL.addInsertAction(Unknown Source)
	at org.hsqldb.Session.addInsertAction(Unknown Source)
	at org.hsqldb.Table.insertSingleRow(Unknown Source)
	at org.hsqldb.StatementDML.insertSingleRow(Unknown Source)
```

Looks like these problems occur only for first inserted object which has ID == 0 ?

**Comment by knstvk** [comment]
Looks like an HSQL-only issue. Try to set "start with 1" when defining identity column in the DB.

**Comment by andreysubbotin** [comment]
The problem relates to 0-ID handling in EclipseLink. As a result, CUBA generates an IDENTITY column that starts from 1. 
Sample CUBA script:
`ID int generated by default as identity(start with 1) not null`
