### ISSUE TITLE
IllegalArgumentException in EntityPicker.removeAllActions method

### ISSUE THREAD

**Issue by daring2** [Haulmont/jmix-ui#730]
Steps to reproduce:
1. Create a screen with entityPicker field.
2. Call removeAllActions method for the field.

Result: IllegalArgumentException is thrown

Stacketrace:
```
Caused by: java.lang.IllegalArgumentException: Incorrect component type. Must be 'EntityPicker' or its inheritors
	at io.jmix.ui.component.EntityPicker$EntityPickerAction.setPicker(EntityPicker.java:74) ~[jmix-ui-1.1.0.jar:na]
	at io.jmix.ui.component.impl.ValuePickerImpl.removeAction(ValuePickerImpl.java:286) ~[jmix-ui-1.1.0.jar:na]
	at io.jmix.ui.component.impl.ValuePickerImpl.removeAllActions(ValuePickerImpl.java:302) ~[jmix-ui-1.1.0.jar:na]
...
```

**Comment by lovtsovaik** [comment]
For QA:

1. Create a screen with entityPicker field
2. Inject entityPicker field to controller
3. Subscribe to init event
4. In OnInit() call removeAllActions() method for the field
5. Run the app
6. Open the screen

**Comment by reznikova21** [comment]
1.2.0-SNAPSHOT - verified
