### ISSUE TITLE
Pivot table loading fails if the table uses nested properties of the association attribute

### ISSUE THREAD

**Issue by gorbunkov** [Haulmont/jmix-ui#772]
If the pivot table uses some nested property:

```xml
<pivot:properties>
     <pivot:property name="person.firstName"/>
</pivot:properties>
```

Then the exception occurs when the screen containing the pivot table is opened.

Exception:
```
Caused by: java.lang.IllegalArgumentException: Property 'person.firstName' not found in Tip
	at io.jmix.core.metamodel.model.impl.MetaClassImpl.getProperty(MetaClassImpl.java:97) ~[jmix-core-1.2.0-SNAPSHOT.jar:na]
	at io.jmix.pivottable.loader.PivotTableLoader.checkValidProperty(PivotTableLoader.java:221) ~[jmix-pivot-table-1.2.0-SNAPSHOT.jar:na]
	at io.jmix.pivottable.loader.PivotTableLoader.loadProperties(PivotTableLoader.java:202) ~[jmix-pivot-table-1.2.0-SNAPSHOT.jar:na]
	at io.jmix.pivottable.loader.PivotTableLoader.loadConfiguration(PivotTableLoader.java:109) ~[jmix-pivot-table-1.2.0-SNAPSHOT.jar:na]
	at io.jmix.pivottable.loader.PivotTableLoader.loadComponent(PivotTableLoader.java:70) ~[jmix-pivot-table-1.2.0-SNAPSHOT.jar:na]
	at io.jmix.ui.xml.layout.loader.ContainerLoader.loadSubComponents(ContainerLoader.java:36) ~[jmix-ui-1.2.0-SNAPSHOT.jar:na]
	at io.jmix.ui.xml.layout.loader.ContainerLoader.loadSubComponentsAndExpand(ContainerLoader.java:74) ~[jmix-ui-1.2.0-SNAPSHOT.jar:na]
	at io.jmix.ui.xml.layout.loader.WindowLoader.loadComponent(WindowLoader.java:85) ~[jmix-ui-1.2.0-SNAPSHOT.jar:na]
	at io.jmix.ui.sys.ScreensImpl.loadWindowFromXml(ScreensImpl.java:319) ~[jmix-ui-1.2.0-SNAPSHOT.jar:na]
	at io.jmix.ui.sys.ScreensImpl.createScreen(ScreensImpl.java:204) ~[jmix-ui-1.2.0-SNAPSHOT.jar:na]
	at io.jmix.ui.sys.ScreensImpl.create(ScreensImpl.java:145) ~[jmix-ui-1.2.0-SNAPSHOT.jar:na]
	at io.jmix.ui.menu.MenuItemCommands$ScreenCommand.createScreen(MenuItemCommands.java:306) ~[jmix-ui-1.2.0-SNAPSHOT.jar:na]
	at io.jmix.ui.menu.MenuItemCommands$ScreenCommand.run(MenuItemCommands.java:242) ~[jmix-ui-1.2.0-SNAPSHOT.jar:na]
	at io.jmix.ui.menu.SideMenuBuilder$MenuCommandExecutor.accept(SideMenuBuilder.java:272) ~[jmix-ui-1.2.0-SNAPSHOT.jar:na]
	at io.jmix.ui.menu.SideMenuBuilder$MenuCommandExecutor.accept(SideMenuBuilder.java:257) ~[jmix-ui-1.2.0-SNAPSHOT.jar:na]
	at io.jmix.ui.component.mainwindow.impl.SideMenuImpl$MenuItemImpl.menuSelected(SideMenuImpl.java:587) ~[jmix-ui-1.2.0-SNAPSHOT.jar:na]
	at io.jmix.ui.widget.JmixSideMenu$1.menuItemTriggered(JmixSideMenu.java:91) ~[jmix-ui-1.2.0-SNAPSHOT.jar:na]
	... 88 common frames omitted
```

Sample project: [jmix-pivot-table-sample.zip](https://github.com/Haulmont/jmix-ui/files/7846101/jmix-pivot-table-sample.zip)

See the [forum topic](https://forum.cuba-platform.com/t/extend-attributes-set-in-pivot/16004)

**Comment by reznikova21** [comment]
1.2.0-SNAPSHOT - verified
